### ISSUE TITLE
Incorrect Placement of Popup Window for ComboBox

### ISSUE THREAD

**Issue by dkartaschew** [mabe02/lanterna#230] opened 2016-04-13 05:14 UTC
Hi,
When using a ComboBox in a dialog that is centered on parent window, the popup window to make the user selection appears in an undesired position when the ComboBox is not in the top-left corner of the dialog.

To replicate:
1. Create a parent window instance, centered on the screen. (Top left is 10,10 on global co-ordinate, and 50x10 in size).
2. Create a dialog box, with a ComboBox underneath several other components. (Top left of dialog is 11,11 on global co-ordinate and is 40x15 in size), ComboBox is 23,12 on relation to the dialog co-ordinate).
3. Open the ComboBox, and the popup window will be displayed, somewhere around 46,25 on the global co-ordinate.

Debugging, the code, the ComboBox uses:
```
popupWindow = new PopupWindow();
popupWindow.setPosition(toGlobal(getPosition().withRelativeRow(1)));
((WindowBasedTextGUI) getTextGUI()).addWindow(popupWindow);
```
However, `toGlobal()` ends up calling `parent.toGlobal(getPosition().withRelative(position))` where `position` is the position of the combobox relative to the dialog...

So the call progress ends up being: (Assuming ComboBox is at position 23,12 relative to the dialog).
```
popupWindow.setPosition(toGlobal(getPosition().withRelativeRow(1)));
popupWindow.setPosition(toGlobal(TerminalPosition(23,13));
... which in AbstractComponent.toGlobal() ends up being:
parent.toGlobal(getPosition().withRelative(TerminalPosition(23,13)));
parent.toGlobal(TerminalPosition(46,25)));
```

With the following modification to ComboBox, we obtained the desired result.
```
popupWindow = new PopupWindow();
popupWindow.setPosition(toGlobal(new TerminalPosition(0, 1)));
((WindowBasedTextGUI) getTextGUI()).addWindow(popupWindow);
```

**Comment by dkartaschew** [comment] 2016-04-13 05:15
Issue is for lanterna-3.0.0beta2

**Comment by mabe02** [comment] 2016-04-17 14:05
Ok, managed to reproduce it. Had some issues first because I tend to wrap them in a border and then it hides the bug.

**Comment by mabe02** [comment] 2016-04-17 14:09
Ok, should be fixed now

**Closed by mabe02** 2016-04-17 14:09 UTC
