### ISSUE TITLE
does not react properly to backspace (terminology)

### ISSUE THREAD

**Issue by NikkyAI** [mabe02/lanterna#277] opened 2016-11-01 15:31 UTC
in Terminology backspace causes 'h' to be written to the textfields
ticking the option to send delte instead of backspaces fixes it 

but i bet there will be some temrinals or cases when this is not a option

**Comment by avl42** [comment] 2016-11-02 01:01
Some pretty old legacy systems, where Backspace produced ^H(0x08) instead
of ^?(0x7f) still exist, and most Terminal(Emulator)s actually allow to
cater for those, but it is fortunately dying out. The defaults are mostly
on ^? these days.

I think it is possible (even if quite complicated) to modify the
InputDecoder (for all StreamBasedTerminals, i.e. not the Awt/Swing
emulators) to translate 0x08 to Backspace.
If you're positive that you really need it, then I'll try to help you.

**Comment by avl42** [comment] 2016-11-02 01:06
PS: In the meantime, if the emulator is set up for ^H, then the ^? sequence can be entered as Ctrl-8 in most Terminal emulations I've come across so far.

**Comment by NikkyAI** [comment] 2016-11-02 01:17
if you are sure it is dying out then i am moe interested in why my terminal emulator uses it by default
and i don't think changing it would be necessary.. 
thanks

**Comment by avl42** [comment] 2016-11-02 01:35
Which terminal emulation are you using?

My judgement of "dying out" was my own experience with (linux)
gnome-terminal and (linux&windows) putty.  Other people's experience might
be different.

Just tested on a Solaris xterm, and it indeed seems to have it the other
way by default,  Modern shells like bash accept either, so maybe lanterna
should just follow that.

**Comment by NikkyAI** [comment] 2016-11-02 01:38
terminal program / emulator ? terminology on linux
using bash and sometimes zsh or csh
tbh i am not entirely sure whats the distinction between the terms terminal emulator and terminal..

**Comment by NikkyAI** [comment] 2016-11-02 01:40
i am playing around with mouse actions in lanterna so i am not using the swing stuff

**Comment by avl42** [comment] 2016-11-02 02:00
The distinction is a legacy itself these days, where there are hardly any
"real" Terminals in use anymore.  In older days, devices were used that had
a screen, a keyboard and a serial interface, but of these devices these
days there might be more on display in museums than in productive use :-)

Lanterna has it's own distinction between "real" and "emulated" terminals.
The distinction here is really that between Lanterna itself emulating a
terminal (AwtTerminal and SwingTerminal  classes in Lanterna) or relying on
the "tty" abstraction (which for Lanterna looks sufficiently well like a
"real" terminal, no matter where the characters actually show up).


I didn't know terminology, but installed it now. (Thanks for bringing it to
my attention, looks cool!).  Anyway, for me it seemed to send ^? by
default. and it also seemed to memorize my settings, unless I first checked
"temporary"...

**Comment by avl42** [comment] 2016-11-02 02:24
If you're going to use Lanterna "gui2" components with mouse, then you
should consider using the freshest sources here from github, because a
nasty bug was just recently fixed and the beta3 doesn't yet have that fix.
(The application crashed whenever you clicked on coordinates that were not
covered by a focusable component.)

But even with the fix, be prepared that mouse-support in standard
components is currently limited to just setting the focus on components.
You cannot (yet) trigger buttons with the mouse, unless you subclass the
components to handle the mouse events yourself.

I just noticed that "mouse move" mode doesn't work with terminology, and
the application suffers a NullPointerException (at ANSITerminal:271) as
soon as the mouse started moving.  The other two modes "mouse click" and
"mouse drag" seem to work fine, at least.

I'll have a closer look at that bug later.

**Comment by NikkyAI** [comment] 2016-11-02 02:26
then i guess my settings were screwed..
PS: try the split and new buttons

**Comment by NikkyAI** [comment] 2016-11-02 14:19
PS: i do use the freshest sources .. gradle and jitpack :D sadly this builds for some reason no sources-jar but i bet thats not a issue on your side
my fix for that is to add a window handles and if component is instanceof button send Enter
sadly this does not work for modal dialogs or dropdown lists or actionlistboxes

**Comment by avl42** [comment] 2016-11-02 15:10
I just analyzed the crash in "mouse move" capture mode with terminology:  when moving the mouse, terminology sends sequences that Lanterna doesn't understand - but instead of discarding them, Lanterna creates bad MouseEvent objects that later crash the application with an NPE...

Btw., "Terminology" is a terrible name for an application when you want to google information about it. ;-)  And I can't even blame google - when you first mentioned it, I also didn't think of it being a terminal emulation's name...

**Comment by NikkyAI** [comment] 2016-11-02 15:41
if we keep chatting is there a irc channel / slack / gitter or so? filling a closed issue with offtopic chat is probably not the best ..

**Comment by avl42** [comment] 2016-11-02 15:47
I'd even re-open it, if github allows you to.

I'm hoping for Martin to step in and decide about ^H and Backspace - hardcoding it into Lanterna would be almost trivial, but then people can no longer use Ctrl-H for anything else (probably shouldn't, anyway)

Also, there is this issue about mouse move capturing with "terminology", which is a legit bug - but I don't know whether in Lanterna, terminology or even both.

I think, we're pretty on-topic here.

**Comment by NikkyAI** [comment] 2016-11-02 15:48
since i only used terminology and the swinggui emulator so far i never have seen what you cna do with mouse movement and dragging.. i assume you can move windows and such ?

**Comment by avl42** [comment] 2016-11-02 16:01
Well, unfortunately not.  Lanterna so far only uses mouseclick events to set the focus on particular interactive components. Nothing else *yet*.

The most straightforward thing to implement would be button-click (including button, checkbox, checkboxlist and radioboxlist). Ways more complicated would be setting the cursorposition in a textbox, and even much more: selecting ranges of text.

Moving around windows by dragging their header or border still looks like pure luxury at this point.

I think any code contribution (PR) would be welcome ;-)

**Comment by NikkyAI** [comment] 2016-11-02 16:04
another thing i noticed with lanterna is that maximizing the window does not raise a resize event..
do i need to listen to something else ?

**Comment by avl42** [comment] 2016-11-02 16:29
Have a look at  src/test/java/com/googlecode/lanterna/issue/Issue274.java (but run it from terminal, not from eclipse!) for a quick feeling of what the mouse can do in Lanterna so far.

Lanterna should receive a signal (SIGWINCH) when you resize the terminology window. It has code to handle this signal and adapt to the new size.  If your components are inside a Window, and the Window isn't itself maximized, then the Window won't know about size changes of the terminal. It is also possible to register a TerminalResizeListener at the Terminal to get your own code triggered on resize.  Note that "Window" and "Terminal" in this paragraph refer to the respective Lanterna classes.

**Comment by NikkyAI** [comment] 2016-11-02 18:24
which terminal emulators have the best mouse support ? i have tried terminology.. obviously failed xfce termn.. no idea what else i even have here..
i should also try what happens when running lanterna inside screen or tmux.. i have a feeling things will break

**Comment by avl42** [comment] 2016-11-02 21:12
The Issue 274 was an issue raised on google groups lanterna about a user's application crashing in some situations regarding mouse & gui.

Before that, the TerminalInputTest was the only one that could be invoked to see Mouse-events at work.

This test case Issue274 makes a simple gui of a textbox, and a few buttons, and activates mouse-click capture mode - originally to trigger the bug reproducibly.  Now that the bug is fixed, Issue274 remains as a test case to see how how barely Lanterna reacts to mouse so far.

**Comment by avl42** [comment] 2016-11-03 19:59
I checked and compared a couple of terminal-emulators w.r.t. mouse support.

bad: putty, xfce4-terminal - if in utf-8 mode, it works only till about column 94 beyond that it sends sequences that get garbled in utf-8 decoding of input. For terminals in e.g. iso-8859-1 mode, it might work up to about column 220 beyond that: chaos.   xfce4-terminal seems to be a spin off of an older gnome-terminal and just lacks some newer features.

ok: urxvt, terminology, gnome-terminal: they can all use utf-8 characters to address up to about 65000 colums.  If used with an 8bit encoding, they might be limited to about 220 like xfce4-terminal.

gnome-terminal and terminology also both support the so-called "sgr 1006" mode, but Lanterna can't make use of that, yet.  I might look into this some day...

I haven't so far tested terminal multiplexers (tmux, screen).

**Comment by avl42** [comment] 2016-11-07 13:09
I seem to have made a mistake in my previous tests...  gnome-terminal behaves like xfce4-terminal wrt reporting columns above 94.

There seems to be a new protocol, which is referred to as the "sgr 1006" mode. gnome-terminal, terminology and putty seem to support it, but urxvt,xfce4 don't yet. It avoids non-ascii characters (at the cost of longer sequences) and I'll try to make lanterna support that, too... (may take a week or so, though)

**Comment by avl42** [comment] 2016-11-15 16:30
@NikkyAI  in the meantime, the fixes for both Ctrl-H and that mouse-move-crash on terminology have been merged, so if you're still on it, retry with latest git version, and with your terminology set for Ctrl-H.

**Comment by mabe02** [comment] 2017-01-15 13:06
Pre-emptively closing this for next release

**Closed by mabe02** 2017-01-15 13:06 UTC
