### ISSUE TITLE
How to "shutdown" the terminal

### ISSUE THREAD

**Issue by schuettec** [mabe02/lanterna#261] opened 2016-08-26 10:42 UTC
Hi, 
I'm using lanterna in an environment that runs a few threads for business logic. Lanterna should run parallel to give an access to maintenance features. So I created a thread where I put the GUI together and invoke `MultiWindowTextGUI.addWindowAndWait(window);`. This thread is then waiting for the GUI to close. The problem is that whenever another thread tries to finish the GUI, the `addWindowAndWait` will not return. I have no chance to shutdown lanterna.
I tried the following:
`
window.close();
screen.stopScreen();
terminal.exitPrivateMode();  
`

This can definitely be my fault, but what am I doing wrong?

**Comment by avl42** [comment] 2016-08-28 14:41
You might need to set the TerminalEmulatorAutoCloseTrigger on the DefaultTerminalFactory:
```
   DefaultTerminalFactory factory = new DefaultTerminalFactory();
   factory.setTerminalEmulatorFrameAutoCloseTrigger(TerminalEmulatorAutoCloseTrigger.CloseOnExitPrivateMode);
```
and use this factory to create the Terminal.

If you create a graphical Terminal directly, you'll probably have to pass this CloseOnExitPrivateMode somewhere to the constructor of the Terminal...

**Comment by schuettec** [comment] 2016-08-30 06:57
Thanks for this hint, I will check if this helps.

**Comment by schuettec** [comment] 2016-08-30 10:55
Okay I don't know nothing about the internals but I found the section where the problem may occur. The method `com.googlecode.lanterna.gui2.MultiWindowTextGUI.waitForWindowToClose(Window)` where the while-loop will run while `window.getTextGUI() != null` will never get null in my case. But I don't know why.

I tried it with the public method `public void setTextGUI(WindowBasedTextGUI textGUI)` but it says the following: 
> Are you calling setTextGUI yourself? Please read the documentation in that case (this could also be a bug in Lanterna, please report it if you are sure you are not calling Window.setTextGUI(..) from your code)

So how is there a chance that `com.googlecode.lanterna.gui2.AbstractWindow.textGUI` will ever get null?

**Comment by schuettec** [comment] 2016-08-31 13:28
I just got the hint from my colleagues that I should additionally tell you, that I have tested your the approach you mentioned above ;-) 
So I tested it but the thread that calls `MultiWindowTextGUI.addWindowAndWait(window);` just won't terminate :(

**Comment by avl42** [comment] 2016-08-31 20:17
You think, the problem is caused by addWindowAndWait, but that is probably wrong. What happens there is, that it is waiting for keystrokes, which can never arrive, because the Terminal Window is already closed.

If you used my previous hints, then closing the terminal window would result in an EOF keystroke to be generated and addWindowAndWait to finish.

When you say:
> I tried the following:
> window.close(); screen.stopScreen(); terminal.exitPrivateMode(); 
then **where** in your code did you put these statements?

**Comment by mabe02** [comment] 2016-09-04 08:31
Hi @schuettec , can you supply a stack dump of the thread that doesn't exit after you closed the GUI? Also, to clarify, are you using the bundled AWT/String terminal emulator or are you running this in a 'real' terminal?

**Comment by schuettec** [comment] 2016-09-04 12:28
Hi, I tried to build you an SSCCE to demonstrate the problem, but now lanterna is doing exactly what I would expect. Tomorrow I will have a look what we are doing wrong at work.

To answer the latest questions:
- We currently testing lanterna with the bundled AWT/Swing terminal
- The statements `window.close(); screen.stopScreen(); terminal.exitPrivateMode();` are invoked from a thread to terminate lanterna. Lanterna was initialized in another thread so that addWindowAndWait can be used without blocking the entire application.

**Comment by schuettec** [comment] 2016-09-05 08:37
Okay I have found the problem and I think it is definetly not a fault of Lanterna. I will explain my solution, because the code is to big to post it as an SSCCE here.

The problem is, that we build a Lanterna GUI in a thread so that we can call `invokeAndWait `without blocking the entire application thread. Please correct me if this isn't neccessary but we do it like this:
`  public static void initTerminal() {
    Thread lanterna = new Thread(new Runnable() {
      public void run() {
        try {
          DefaultTerminalFactory factory = new DefaultTerminalFactory();
          terminal = factory.createTerminal();
          screen = new TerminalScreen(terminal);
          screen.startScreen();
          panel = new Panel();
          panel.setLayoutManager(new GridLayout(2));
          panel.addComponent(new Label("Forename"));
          panel.addComponent(new TextBox());
          panel.addComponent(new Label("Surname"));
          panel.addComponent(new TextBox());
          panel.addComponent(new EmptySpace(new TerminalSize(0, 0)));
          panel.addComponent(new Button("Submit"));
          window = new BasicWindow();
          window.setComponent(panel);
          gui = new MultiWindowTextGUI(screen, new DefaultWindowManager(), new EmptySpace(TextColor.ANSI.BLUE));
          gui.addWindowAndWait(window);
        } catch (Exception e) {
          e.printStackTrace();
        }
      }
    }, GUI_THREAD_NAME);
    lanterna.start();
  }`

The problem is simple: We missed to synchronize the `initTerminal` method. If the shutdown process takes place, when lanterna is not fully initialized, the shutdown cannot close a window or exit private mode, because at this time there may be no window and/or no terminal. This is simply our synchronization fault. I fixed this already so it works now.

But one question remains: If I do not create a thread and use `addWindow()` only, there is no thread or something that handles user inputs isn't it? Lanterna is showing a GUI with no elements visible.

**Comment by mabe02** [comment] 2016-09-22 12:23
I tried to run your code (two slight modifications) without any extra threads and it works well for me:
```java
    public static void main(String[] args) {
        try {
            DefaultTerminalFactory factory = new DefaultTerminalFactory();
            Terminal terminal = factory.createTerminal();
            Screen screen = new TerminalScreen(terminal);
            screen.startScreen();
            Panel panel = new Panel();
            panel.setLayoutManager(new GridLayout(2));
            panel.addComponent(new Label("Forename"));
            panel.addComponent(new TextBox());
            panel.addComponent(new Label("Surname"));
            panel.addComponent(new TextBox());
            panel.addComponent(new EmptySpace(new TerminalSize(0, 0)));
            final Window window = new BasicWindow();
            panel.addComponent(new Button("Submit", new Runnable() {
                @Override
                public void run() {
                    window.close();
                }
            }));
            window.setComponent(panel);
            MultiWindowTextGUI gui = new MultiWindowTextGUI(screen, new DefaultWindowManager(), new EmptySpace(TextColor.ANSI.BLUE));
            gui.addWindowAndWait(window);
            screen.stopScreen();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
```

When you select the button, the addWindowAndWait(..)-method returns, I've added a line to stop the screen (essentially same as exiting out of private mode for the terminal object) and it closes the Swing window.

**Comment by mabe02** [comment] 2017-02-15 13:04
Stale, closing...

**Closed by mabe02** 2017-02-15 13:04 UTC
