### ISSUE TITLE
NPE after switch from beta to SNAPSHOT version

### ISSUE THREAD

**Issue by celyo** [mabe02/lanterna#249] opened 2016-08-05 15:38 UTC
Hi,

I've got NullPointerException after I've made a switch from beta vertion to snapshot version.
The happens at the application start and here is it:

`Exception in thread "main" java.lang.NullPointerException
	at com.googlecode.lanterna.gui2.WindowShadowRenderer.postRender(WindowShadowRenderer.java:51)
	at com.googlecode.lanterna.gui2.MultiWindowTextGUI.drawGUI(MultiWindowTextGUI.java:271)
	at com.googlecode.lanterna.gui2.AbstractTextGUI.updateScreen(AbstractTextGUI.java:120)
	at com.googlecode.lanterna.gui2.MultiWindowTextGUI.updateScreen(MultiWindowTextGUI.java:219)
	at com.googlecode.lanterna.gui2.AbstractTextGUIThread.processEventsAndUpdate(AbstractTextGUIThread.java:83)
	at com.googlecode.lanterna.gui2.MultiWindowTextGUI.waitForWindowToClose(MultiWindowTextGUI.java:401)
	at com.googlecode.lanterna.gui2.AbstractWindow.waitUntilClosed(AbstractWindow.java:268)
	at com.googlecode.lanterna.gui2.MultiWindowTextGUI.addWindowAndWait(MultiWindowTextGUI.java:368)
	at org.celyo.jdbconsole.MainApp.main(MainApp.java:52)
`

**Comment by avl42** [comment] 2016-08-05 21:33
Thanks for reporting!

Can you reproduce the problem with one of the lanterna test-apps or can you
give us a small demo app?

Does the problem show immediately after app start, or only after some
action in the app or maybe after resizing the window?

**Comment by celyo** [comment] 2016-08-08 12:17
Hi,

It happens on application start.
Here is an example code:
`
public class MainApp {

  public static void main(String[] args) throws IOException {
    Terminal terminal = new DefaultTerminalFactory().createTerminal();
    Screen screen = new TerminalScreen(terminal);
    MultiWindowTextGUI gui = new MultiWindowTextGUI(screen, new DefaultWindowManager(),
            new EmptySpace(TextColor.ANSI.BLUE));
    
    TerminalSize screenSize = screen.getTerminalSize();

    BasicWindow window = new BasicWindow();

    Panel mainPanel = new Panel();
    mainPanel.setPreferredSize(screenSize);

    window.setComponent(mainPanel);

    gui.addWindowAndWait(window);
  }
}

`

**Comment by avl42** [comment] 2016-08-10 00:47
The easiest avoidable part of the problem is, that you set the size of the Panel to screensize, while the Panel sits inside a Window with some borders.  Changing this such that the Window will fit completely within screen should fix this appearance of the bug, just so it doesn't block you.

Second key to being affected by this bug is using a Theme that happens to have the "TRANSPARENT" property set to true - which is obviously the case for the default Theme. I think to remember that the default Theme was fairly recently changed, and maybe the previous default Theme didn't use this property - just guessing here.

The real solution would be to add some checks in WindowShadowRenderer.postRender, so that if the lower end of screen (or the right side!) of the decorated window is off-screen, and useTransparency is true, then the TextCharacter reference should be saved to a local var, and it's getCharacter() only invoked if not-null.
current:
`
            if(useTransparency) {
                characterToDraw = textGraphics.getCharacter(upperRight.getColumn(), row).getCharacter();
            }
` should become something like '
            if(useTransparency) {
                TextCharacter tc = textGraphics.getCharacter(upperRight.getColumn(), row);
                if (tc != null) { characterToDraw = tc.getCharacter(); }
            }
'
There are 3 such spots (and these three are not all same!)

I'll make a PR for this...

**Comment by mabe02** [comment] 2016-08-18 13:02
Yes, that looks correct, thanks!

**Comment by mabe02** [comment] 2016-08-18 13:03
I'm preemptively closing this, please re-open if this still isn't working for you

**Closed by mabe02** 2016-08-18 13:03 UTC
