### ISSUE TITLE
Window Scrolling in Putty

### ISSUE THREAD

**Issue by chrsdbll** [mabe02/lanterna#204] opened 2016-02-04 18:58 UTC
Using Putty, when the GUI Window is larger than the putty window, a notification to use the Ctrl+Arrow is displayed. However, Putty intercepts the Ctrl+Arrow commands, which prevents scrolling.

**Comment by avl42** [comment] 2016-02-05 02:54
putty in particular sends `^[[A` for plain CursorUp and `^[OA` for Ctrl-Cursor.

During my work on simplifying the input parser, I checked a couple of terminal-emulators, and there were some that would send these two sequences just the other way round. That's why the current implementation doesn't distinguish `O` from `[` as second letter of escape sequences at all, thus spoiling Ctrl modifier recognition on certain terminals.

I just checked, that `^[OA` also wasn't recognized before my changes, so my changes at least didn't cause a regression -  phew ;-)  Previously, Ctrl-ArrowUp on putty would have produced separate `Esc`, `O`, `A` KeyStrokes.

One approach to improve things might be a custom KeyDecodingProfile that would try to parse the output of system program `infocmp` for the current value of environment variable `TERM` and generate the specific patterns. With putty often maskerading as xterm, I'm not too sure if that would even help.

**Comment by mabe02** [comment] 2016-02-06 08:08
We could make the scrolling keys customizable, but it feels like that just moves the problem from the library to the user. Still it's hard to find a combination that works for all emulators.

**Comment by mabe02** [comment] 2016-02-11 14:15
If anyone has any suggestions on this, I'm all ears. I suppose we can go with ALT+arrows? Seems like shift+arrows only works with left and right arrow for some reason...

**Comment by avl42** [comment] 2016-02-11 14:30
shift arrows are sometimes defined to scroll the terminal by single lines.

putty sends shift cursor exactly like ctrl cursor, and alt cursor is like
esc+cursor, so that would be a viable solution for all terminals. (other
terminals are less restricting than putty in the first place).

btw., even if the terminal does send proper sequences for ctrl and shift
cursor, then using a multiplexer like tmux would still spoil ctrl cursor.

**Comment by mabe02** [comment] 2016-02-12 12:12
OK, let's try ALT+arrows unless we can come up with anything better

**Comment by mabe02** [comment] 2016-02-12 12:17
I've pushed change to use ALT instead of CTRL, pre-emptively closing this but please re-open if it doesn't work

**Comment by avl42** [comment] 2016-02-12 19:33
The commit-message is a bit misleading, because putty doesn't "capture" ctrl-arrow. it just sends it in a confusing and ambiguous way.
If on the shell prompt, typing Ctrl-V and:
    plain arrow -> `^[[A`,  ctrl-arrow -> `^[OA`
if in application mode (e.g. within vi input mode), typing Ctrl-V and:
    plain arrow -> `^[OA`,  ctrl-arrow -> `^[[A`

I can't tell if lanterna is in "application" mode, or not, so I'd have a 50%
chance of guessing it wrong.  Therefore `O` and `[` are treated the same.

**Comment by avl42** [comment] 2016-02-12 19:34
Oh, and you probably should update the help-text (bottom line when scrollbars are shown), too. :-)

**Comment by mabe02** [comment] 2016-02-13 11:23
Okay, the thought the issue was that ctrl+arrow was intercepted by putty and didn't get sent through? Sorry, I have to re-read this again...

**Comment by mabe02** [comment] 2016-02-13 12:14
I've updated the help text, going to try this out with Putty now (somehow...) and see if it works

**Comment by mabe02** [comment] 2016-02-13 12:47
Okay, so Putty uses different codes depending on if the application is in "application" mode or not? This must be the same as private mode! The input decoder has no way of knowing this, but I suppose that's something we could add.

**Comment by mabe02** [comment] 2016-02-13 12:54
Nah, I still get `^[[A` for plain CursorUp and `^[OA` for ctrl/shift CursorUp in private mode. Were you able to get the reverse somehow?

**Comment by avl42** [comment] 2016-02-13 12:57
I'm not saying it's impossible...
We could let the inputdecoder know, but that's not yet enough. We also need
to let the CharacterPattern know, e.g. add another argument to match-method.

PS: seeing your next question in the notifications... as i wrote somewhere:
in vi go to insert mode and type ctrl-v and cursorup.

**Comment by avl42** [comment] 2016-02-13 13:03
I don't actually understand that application mode. i also thought it would
be a synonym of private mode. If that isn't so, then it would be feasible
to modify the sequence-pattern to map the O to, well, either control or
shift, as putty doesn't distinguish that.  Still, there are also sequences
that always have the O (iirc, some of the function keys) so we'd have to
identify for which keys the O means modified, and where not.

**Comment by mabe02** [comment] 2016-02-13 13:03
Okay, now I see it too. Tempted to add `^[OA` (and the others) to `DefaultKeyDecodingProfile` for now as CTRL/Shift+arrow until someone figures out how Putty decides if it's in "reverse" mode.

**Comment by avl42** [comment] 2016-02-13 13:05
This is now in EscapeSequencePattern.

**Comment by avl42** [comment] 2016-02-13 13:07
well, i mean, Esc...Pattern is now the place to do it. it's not yet added
there, of course.

**Comment by avl42** [comment] 2016-02-13 13:09
I'll probably get to it in about an hour. Only on my tablet right now.

**Comment by mabe02** [comment] 2016-02-13 13:11
Okay, if you could put in a pull request when you have a chance, that would be great. I'll release beta 2 after that. Thanks!

**Comment by avl42** [comment] 2016-02-13 14:59
Ok, here is some analysis, PR follows immediately afterwards.

The "application mode" (that vim uses, where I saw the logic inverted) is related to terminfo's "keypad_xmit" (short: smkx) with description "enter 'keyboard_transmit' mode".

The actual terminfo entry for xterm maps this code to: `\E[?1h\E=`, which is really two sequences: `\E[?1h` is the one that reverses the ctrl-logic for the cursor keys, and `\E`= switches the numeric keypad to entirely different and not yet supported sequences. Even NumLock,/,*,- keys in the top-row of the number-pad then get mapped. Unfortunately to the same sequences that are F1,F2,F3,F4 on other terminals.

We can only hope, that we don't accidentally stumble into that mode.

Assuming that we keep out of it, you can now almost hold your breath for the PR.

**Comment by mabe02** [comment] 2016-02-13 15:29
According to http://www.tldp.org/HOWTO/Keyboard-and-Console-HOWTO-21.html, we can send `\E[?1l` to reset the keyboard back to non-application mode. We could print as a starting sequence to make sure it's not set, which would of course cause some issues if the user expects this state to be kept intact after starting and finishing a lanterna-based application. On the other hand, lanterna wouldn't function properly (or at least not for programs that needs to distinguish between arrow keys and ctrl+arrow keys). Maybe merge, leave it for now and acknowledge that we can't protect ourselves against every single weird terminal state...?

**Comment by avl42** [comment] 2016-02-13 15:42
Let's just await and see if it ever becomes an issue... ;-)

**Comment by mabe02** [comment] 2016-02-13 15:49
Agreed :)

**Closed by mabe02** 2016-02-13 15:49 UTC
