### ISSUE TITLE
When running jdk-headless, Lanterna fails immediately

### ISSUE THREAD

**Issue by spatula75** [mabe02/lanterna#170] opened 2015-08-19 23:41 UTC
If a headless JDK/JRE is installed, Lanterna will experience a java.lang.ExceptionInInitializerError at DefaultTerminalFactory.java:85, which is caused by a java.lang.NullPointerException being thrown by sun.awt.FontConfiguration.getVersion call which happens when SwingTerminalFontConfiguration.java:197 calls isFontMonospaced during construction.

There should be a if (!GraphicsEnvironment.isHeadless()) { } around the SwingTerminalFrame initializers in the DefaultTerminalFactory constructor to avoid this problem.

**Comment by avl42** [comment] 2015-08-20 08:23
Indeed...  

@mabe02 I think it would be best to initialize all the SwingXyzConfiguration-typed xyzConfiguration fields to null instead of SwingXyzConfiguration.DEFAULT, and only have the SwingTerminalFrame constructor itself replace nulls by appropriate DEFAULT instances.

@spatula75 It would be helpful, if you could just try to edit your local DefaultTerminalFactory.java and replace the ...DEFAULT expressions around line 85 by null and check whether that already works for you - and report.  If it still doesn't, then you have no choice than instantiate your specific Terminal class directly and not use the DefaultTerminalFactory class at all for a headless VM.  (Even in that case, my suggestions to mabe02 remains valid.)

As it is, the DefaultTerminalFactory causes the SwingXyzConfiguration classes to be loaded *and initialized*, even if Swing is not used.

This problem doesn't seem to hurt if merely DISPLAY is unset (on unix-like systems), but it apparently does hurt, if the Java VM is an entirely headless one (that doesn't contain most of the swing classes - I haven't yet run into such, myself).

**Comment by mabe02** [comment] 2015-08-22 02:12
Out of curiosity, what JDK/JRE are you using?

**Comment by spatula75** [comment] 2015-08-22 15:02
This was observed using openjdk-7-jdk-headless on Ubuntu.

On 21 August 2015 at 19:12, mabe02 <notifications@github.com> wrote:

> Out of curiosity, what JDK/JRE are you using?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mabe02/lanterna/issues/170#issuecomment-133626441>.
>



-- 
"Courage isn't just a matter of not being frightened, you know. It's being
afraid and doing what you have to do anyway."
   -- Doctor Who - Planet of the Daleks
This message has been brought to you by Nick Johnson 2.3b1 and the number 6.

**Comment by avl42** [comment] 2015-08-22 15:25
@spatula75  Any results? Does replacing the "...DEFAULT" by "null" solve it for headless?

**Comment by moraesmv** [comment] 2015-09-22 17:12
I am working on a command line interface for a platform for my company, and they are interested on this software.
I have tested a couple of the examples from the documentation, but every single one creates a separate window from the terminal i am calling the program. 
is there a way to execute the graphical interface on the same terminal it is called from? an example of this behavior would be to open a text editor like nano via ssh connection.
My boss call it headless, i am a new developer so i never heard about this type of code before.
Any help will be appreciated
Thanks for any information.

**Comment by viktor-podzigun** [comment] 2015-09-23 10:25
Usually you can emulate headless mode (on servers running without GUI you don't have to do it, its enabled by default) by specifying this property when running your application:
```bash
java -Djava.awt.headless=true -jar yourapp.jar
```
Hope this helps.

**Comment by avl42** [comment] 2015-09-27 14:26
@moraesmv Have you tried the master branch on github?  There was a fairly recent (one or two months ago) change to prefer UnixTerminal over Swing when available, and when I start some lanterna-example from a terminal it now remains inside the terminal (unless I redirect input from /dev/null).

This change might not yet be in any versioned jar-ball.

**Comment by mabe02** [comment] 2015-09-28 11:52
@spatula75, could you try again with the latest master branch? I've re-arranged the code a bit to delay static initialization of some of the Swing related classes (a variation of what you suggested @avl42, let's try it and take it one step further if that doesn't work). Also, please attach a full stack trace if you still get an error.

**Comment by mabe02** [comment] 2015-09-28 11:54
@moraesmv as @avl42 is saying, the latest code on master (which isn't released on maven yet) has better auto-detection of if you are running it from an IDE or from a real terminal. Please give it a try if you can.

**Comment by avl42** [comment] 2015-09-28 13:09
I must admit I doubt that this patch will solve it.  Calling the static method getDefault() will still cause the SwingXxxConfiguration classes to be loaded and instantiated, and this will likely continue to fail on a pure headless installation.

**Comment by mabe02** [comment] 2015-09-29 11:55
Ok, so get rid of any reference to these classes from DefaultTerminalFactory then, that should avoid the ClassLoader from picking them up and implicitly try to load the Swing classes? I must say, I'm not a 100% sure on how this part of the JVM works...

**Comment by mabe02** [comment] 2015-09-29 11:58
Well, it's can't be just that, because then we can't refer to SwingTerminalFrame either, since that class pulls in lots of Swing classes too. I guess the problem is the SwingTerminalFontConfiguration class, because it instatiates a couple of static Font fields, probably during class load time. Let's get rid of those and see if that works.

**Comment by mabe02** [comment] 2015-09-29 12:04
There, pushed some more code with the static Font initializers removed from SwingTerminalFontConfiguration. Try again with latest master @spatula75 ?

**Comment by avl42** [comment] 2015-09-29 20:15
The changes are in the right direction, but not yet enough.

The problem is, that the DefaultTerminalFactory constructor still tries to get a fontConfiguration, even though it might not use it at all.  That very attempt to get a fontConfiguration already breaks it all for purely headless VMs.

My suggestion here was to leave the fontConfiguration initially at null. If it turns out that a SwingTerminal **is** to be created, and the program didn't explicitly set a custom fontConfiguration, then simply pass that *null* to the SwingTerminal, and let the SwingTerminal itself replace null by a default instance. Or, if you want to guarantee non-null values, then you could add this line:

    if (fontConfiguration == null) { fontConfiguration = SwingTerminalFontConfiguration.getDefault(); }

to the DTF, immediately before the "new SwingTerminalFrame(...)" call.

Everything I wrote about fontConfiguration also applies to colorConfiguration and deviceConfiguration.

There is no point in getting SwingTerminal default-configuration objects, while the decision about type of Terminal to create hasn't been made in favour of a SwingTerminal.

**Comment by avl42** [comment] 2015-09-29 20:29
PS: class loading is defined to be lazy.  Merely mentioning a class doesn't mean it will get loaded. But if a class is actually used (e.g. by accessing static members, calling static methods, or instantiating it), then it will be loaded.  This is what currently still happens in the DefaultTerminalFactory: it is *using* the configuration classes (by calling their getDefault() ), even before deciding on the Terminal to create.

**Comment by mabe02** [comment] 2015-10-25 15:05
Ok, that makes sense. I've updated the code again to make sure DefaultTerminalFactory doesn't instantiate any of the Swing classes. No reply from @spatula75 though.

**Comment by spatula75** [comment] 2015-10-25 15:10
Sorry, I haven't had a chance to look at it again since our initial
discussion. It sounds like that fix would probably work. I may be able to
find time this week to try it, or if you want to try to duplicate the
conditions in which we saw the trouble, running it against the
openjdk-7-jre-headless Debian package should be all it takes.

**Comment by mabe02** [comment] 2016-02-11 14:10
So I did try this with openjdk-7-jre-headless on Debian and I didn't get the ExceptionInInitializerError as you did above, rather I got a java.awt.HeadlessException with I tried to force it to run the Swing version, which seems to me like openjdk-7-jre-headless isn't as headless as it makes out to be... Running through the console version seems to work fine, so I'm going to close this issue now. Please re-open or create a new issue if you find it's still not working.

**Closed by mabe02** 2016-02-11 14:10 UTC
